### ISSUE TITLE
Cannot find module 'persian-date'

### ISSUE THREAD

**Issue by faridfedora** [babakhani/PersianDate#43]
Hello, I installed persian-date with npm but  when I wanna use your module I get this error:
Error: Cannot find module 'persian-date'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/........./start.js:3:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

thanks in advance

**Comment by AminMMZ** [comment]
I've had this problem too
this can be fixed by adding `"main": "src/pDate"` to this project's package.json file
because I need this feature right now I'm going to fork this repo and do the change.

**Comment by faridfedora** [comment]
Thanks bro, it worked!
